### ISSUE TITLE
Please submit code to the main repo

### ISSUE THREAD

**Issue by Ani-ki** [Luna664/Anamnesis#1]
If there are localisation issues with the main repo, it would be better if you did a pull request so we can make them part of the project.

**Comment by Luna664** [comment]
I'll see to make it, but for the moment it's a big DIY, I'm waiting to make something cleaner to propose it on the main repo ^^

**Comment by Luna664** [comment]
Well, I can't find how to make a pull request on the main repo, so I made it on mine if you want to have a look at it

https://github.com/Luna664/Anamnesis/pull/2
